const Auth = {
  FAIL_REQUEST_AUTH  : 'FAIL_REQUEST_AUTH',
  REQUEST_AUTH_LOGIN : 'REQUEST_AUTH_LOGIN',
  AUTH_LOGIN         : 'AUTH_LOGIN',
  REQUEST_AUTH_LOGOUT: 'REQUEST_AUTH_LOGOUt',
  AUTH_LOGOUT        : 'AUTH_LOGOUT'
}

export default Auth
