const Auth = {
  FAIL_REQUEST_AUTH: 'FAIL_REQUEST_AUTH',

  REQUEST_LOGIN : 'REQUEST_LOGIN',
  LOGIN         : 'LOGIN',
  REQUEST_LOGOUT: 'REQUEST_LOGOUT',
  LOGOUT        : 'LOGOUT'
}

export default Auth
